[currpairs]
g10_currpairs = EURUSD,AUDUSD,NZDUSD,GBPUSD,USDJPY,USDCHF,USDCAD
asia_deliv_currpairs = USDCNH,USDSGD,USDHKD,USDTHB
asia_nd_currpairs = USDKRW,USDINR,USDIDR,USDTWD,USDPHP
aud_cross_currpairs = EURAUD,GBPAUD,AUDNZD,AUDJPY,AUDCAD

[ccys]
g10_ccys = EUR,AUD,NZD,GBP,JPY,CHF,CAD
asia_deliv_ccys = CNH,SGD,HKD,THB
asia_nd_ccys = KRW,INR,IDR,TWD,PHP

; [bbg_tickers1]
; asia_ndfs = {
;     "USDKRW": "KWN+1M Curncy",
;     "USDINR": "IRN+1M Curncy",
;     "USDIDR": "IHN+1M Curncy",
;     "USDTWD": "NTN+1M Curncy",
;     "USDPHP": "PPN+1M Curncy",
;     }
; deliv_fwds = {
;     "USDCNH": "CG+1M Curncy",
;     "USDSGD": "SGD+1M Curncy",
;     "USDHKD": "HD+1M Curncy",
;     "USDTHB": "TBO+1M Curncy"
;     }

bbg_imp_yields = {
    "USD": {'1W': 'USOSFR1Z Curncy', '2W': 'USOSFR2Z Curncy', '1M': 'USOSFRA Curncy', '2M': 'USOSFRB Curncy', '3M': 'USOSFRC Curncy', '6M': 'USOSFRF Curncy', '9M': 'USOSFRI Curncy', '1Y': 'USOSFR1 Curncy'},
    "INR": {'1W': 'IRNI1W Curncy', '2W': 'IRNI2W Curncy', '1M': 'IRNI1M Curncy', '2M': 'IRNI2M Curncy', '3M': 'IRNI3M Curncy', '6M': 'IRNI6M Curncy', '9M': 'IRNI9M Curncy', '1Y': 'IRNI12M Curncy'},
    "KRW": {'1W': 'KWNI1W Curncy', '2W': 'KWNI2W Curncy', '1M': 'KWNI1M Curncy', '2M': 'KWNI2M Curncy', '3M': 'KWNI3M Curncy', '6M': 'KWNI6M Curncy', '9M': 'KWNI9M Curncy', '1Y': 'KWNI12M Curncy'},
    "TWD": {'1W': 'TRNI1W Curncy', '2W': 'TRNI2W Curncy', '1M': 'TRNI1M Curncy', '2M': 'TRNI2M Curncy', '3M': 'TRNI3M Curncy', '6M': 'TRNI6M Curncy', '9M': 'TRNI9M Curncy', '1Y': 'TRNI12M Curncy'},
    "IDR": {'1W': 'IHNI1W Curncy', '2W': 'IHNI2W Curncy', '1M': 'IHNI1M Curncy', '2M': 'IHNI2M Curncy', '3M': 'IHNI3M Curncy', '6M': 'IHNI6M Curncy', '9M': 'IHNI9M Curncy', '1Y': 'IHNI12M Curncy'},
    "PHP": {'1W': 'PPNI1W Curncy', '2W': 'PPNI2W Curncy', '1M': 'PPNI1M Curncy', '2M': 'PPNI2M Curncy', '3M': 'PPNI3M Curncy', '6M': 'PPNI6M Curncy', '9M': 'PPNI9M Curncy', '1Y': 'PPNI12M Curncy'},
    "THB": {'1W': 'TBOI1W Curncy', '2W': 'TBOI2W Curncy', '1M': 'TBOI1M Curncy', '2M': 'TBOI2M Curncy', '3M': 'TBOI3M Curncy', '6M': 'TBOI6M Curncy', '9M': 'TBOI9M Curncy', '1Y': 'TBOI12M Curncy'},
    "CNH": {'1W': 'CG1W Curncy', '2W': 'CG2W Curncy', '1M': 'CG1M Curncy', '2M': 'CG2M Curncy', '3M': 'CG3M Curncy', '6M': 'CG6M Curncy', '9M': 'CG9M Curncy', '1Y': 'CG12M Curncy'},
    "SGD": {'1W': 'SGD1W Curncy', '2W': 'SGD2W Curncy', '1M': 'SGD1M Curncy', '2M': 'SGD2M Curncy', '3M': 'SGD3M Curncy', '6M': 'SGD6M Curncy', '9M': 'SGD9M Curncy', '1Y': 'SGD12M Curncy'},
    "HKD": {'1W': 'HDI1W Curncy', '2W': 'HDI2W Curncy', '1M': 'HDI1M Curncy', '2M': 'HDI2M Curncy', '3M': 'HDI3M Curncy', '6M': 'HDI6M Curncy', '9M': 'HDI9M Curncy', '1Y': 'HKD12M Curncy'},
    "EUR": {'1W': 'EUI1W Curncy', '2W': 'EUI2W Curncy', '1M': 'EUI1M Curncy', '2M': 'EUI2M Curncy', '3M': 'EUI3M Curncy', '6M': 'EUI6M Curncy', '9M': 'EUI9M Curncy', '1Y': 'EUI12M Curncy'},
    "JPY": {'1W': 'JYI1W Curncy', '2W': 'JYI2W Curncy', '1M': 'JYI1M Curncy', '2M': 'JYI2M Curncy', '3M': 'JYI3M Curncy', '6M': 'JYI6M Curncy', '9M': 'JYI9M Curncy', '1Y': 'JYI12M Curncy'},
    "GBP": {'1W': 'GPI1W Curncy', '2W': 'GPI2W Curncy', '1M': 'GPI1M Curncy', '2M': 'GPI2M Curncy', '3M': 'GPI3M Curncy', '6M': 'GPI6M Curncy', '9M': 'GPI9M Curncy', '1Y': 'GPI12M Curncy'},
    "AUD": {'1W': 'ADI1W Curncy', '2W': 'ADI2W Curncy', '1M': 'ADI1M Curncy', '2M': 'ADI2M Curncy', '3M': 'ADI3M Curncy', '6M': 'ADI6M Curncy', '9M': 'ADI9M Curncy', '1Y': 'ADI12M Curncy'},
    "NZD": {'1W': 'NDI1W Curncy', '2W': 'NDI2W Curncy', '1M': 'NDI1M Curncy', '2M': 'NDI2M Curncy', '3M': 'NDI3M Curncy', '6M': 'NDI6M Curncy', '9M': 'NDI9M Curncy', '1Y': 'NDI12M Curncy'},
    "CHF": {'1W': 'SFI1W Curncy', '2W': 'SFI2W Curncy', '1M': 'SFI1M Curncy', '2M': 'SFI2M Curncy', '3M': 'SFI3M Curncy', '6M': 'SFI6M Curncy', '9M': 'SFI9M Curncy', '1Y': 'SFI12M Curncy'},
    "CAD": {'1W': 'CDI1W Curncy', '2W': 'CDI2W Curncy', '1M': 'CDI1M Curncy', '2M': 'CDI2M Curncy', '3M': 'CDI3M Curncy', '6M': 'CDI6M Curncy', '9M': 'CDI9M Curncy', '1Y': 'CDI12M Curncy'}
    }

[fixingcuts]
bbg_fixing_cut = BFIX_TKY3PM,BFIX_LDN4PM,BFIX_NY10AM,FIXINGS_ASIA

[tenors]
bbg_tenors_list = ON,1W,2W,1M,2M,3M,6M,9M,1Y
bbg_poins_tenors_list = 1W,2W,1M,2M,3M,6M,9M,1Y

[bbg_sources]
vol_source = {"XXXYYY": "BGN","USDPHP": "BGNT"}

[points_short_names]
short_names = {"EURUSD": "EUR","AUDUSD": "AUD","USDJPY": "JPY","USDCHF": "CHF","USDCAD": "CAD","USDCNH": "CNH","USDSGD": "SGD","USDHKD": "HKD","USDTHB": "THB","USDKRW": "KWN","USDINR": "IRN","USDIDR": "IHN","USDTWD": "TRN","USDPHP": "PPN","EURAUD": "EURAUD","GBPAUD": "GBPAUD","AUDNZD": "AUDNZD","AUDJPY": "AUDJPY","AUDCAD": "AUDCAD"}